name: Pre-Commit update
run-name: "Update Pre-Commit dependencies"

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 1 * *  # 1am of every 1st day of every month

jobs:
  update:
    name: "Update Pre-Commit dependencies"
    uses: ./.github/workflows/_pre-commit-update.yml

  comment-pr:
    name: Give comment on the PR after dependency update
    needs: [update]
    if: always() && (needs.update.outputs.pr_operation == 'created' || needs.update.outputs.pr_operation == 'updated')
    uses: ./.github/workflows/_comment_pr.yml
    with:
      pr_number: ${{ needs.update.outputs.pr_number }}
      job_result: ${{ needs.update.result }}